apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-app
          image: devleoperj/order-app:v1
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE-URL
              value: jdbc:mysql://order-mysql-service:3308/order-db
            - name: SPRING_DATASOURCE-USERNAME
              value: root
            - name: SPRING-DATASOURCE-PASSWORD
              value: "1234"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - port: 80
      targetPort: 8081
