apiVersion: v1
kind: Service
metadata:
  name: order-mysql-service
spec:
  selector:
    app: order-mysql
  ports:
    - port: 3308
      targetPort: 3308
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-mysql-service
spec:
  selector:
    matchLabels:
      app: order-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: order-mysql
    spec:
      containers:
        - name: order-mysql
          image: mysql:8.0
          ports:
            - containerPort: 3307
          volumeMounts:
            - mountPath: /etc/mysql/conf.d
              name:   mysql-config
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_DATABASE
              value: "order-db"
      volumes:
        - name: mysql-config
          configMap:
            name: order-mysql-config

