---
apiVersion: v1
kind: Service
metadata:
  name: customer-mysql-service
spec:
  selector:
    app: customer-mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-mysql-service
spec:
  selector:
    matchLabels:
      app: customer-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_DATABASE
              value: "customer-db"
